# Generated by Django 5.1.6 on 2025-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_emi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emi",
            name="category",
        ),
        migrations.AlterField(
            model_name="emi",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Semi-Annual", "Semi-Annual"),
                    ("Annual", "Annual"),
                ],
                max_length=20,
            ),
        ),
    ]
